version: "3.9"

services:

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: keycloak
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8099:8080"
    volumes:
      - ./keycloak-realm.json:/opt/keycloak/data/import/realm.json

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # web UI
    environment:
      RABBITMQ_DEFAULT_USER: igloo
      RABBITMQ_DEFAULT_PASS: igloo
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbitmq_management load_definitions "/etc/rabbitmq/definitions.json"
    volumes:
      - ./rabbitmq-definitions.json:/etc/rabbitmq/definitions.json

  postgres-bar:
    image: postgres:15
    container_name: postgres-bar
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bar
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  postgres-inventory:
    image: postgres:15
    container_name: postgres-inventory
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: inventory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
